/*
******************************************************************************
File:     main.c
Info:     Generated by Atollic TrueSTUDIO(R) 9.3.0   2022-07-21

The MIT License (MIT)
Copyright (c) 2019 STMicroelectronics

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.

******************************************************************************
*/


/*
 * this program is for porting FreeRTOS with STM32F103C8
 * in this project we created four tasks to see their behavior
 * each two tasks use hardware resource 7-segment to display numbers to it
 * we use Mutex for every 7-segment because every two tasks can share 7-segment
*/



/* Includes */
#include "STD_TYPES.h"
#include "BIT_MATH.h"

#include "RCC_interface.h"
#include "DIO_interface.h"
#include "SEVSEG_interface.h"


#include "FreeRTOS.h"
#include "task.h"
#include "semphr.h"



#define TASK1_PRIORITY		(4)
#define TASK2_PRIORITY		(4)
#define TASK3_PRIORITY		(4)
#define TASK4_PRIORITY		(4)



TaskHandle_t task1_handle = NULL , task2_handle = NULL , task3_handle = NULL , task4_handle = NULL;

SemaphoreHandle_t SevSeg_1 = NULL , SevSeg_2 = NULL;


void task1(void *pvParameter);
void task2(void *pvParameter);
void task3(void *pvParameter);
void task4(void *pvParameter);

void system_init(void);



int main(void)
{
	system_init();


	/* create semaphores */
	SevSeg_1 = xSemaphoreCreateMutex();
	SevSeg_2 = xSemaphoreCreateMutex();
	/* create tasks */

	BaseType_t task1_ret , task2_ret , task3_ret , task4_ret;

	task1_ret = xTaskCreate(task1,"task1",configMINIMAL_STACK_SIZE,NULL,TASK1_PRIORITY,&task1_handle);
	task2_ret = xTaskCreate(task2,"task2",configMINIMAL_STACK_SIZE,NULL,TASK2_PRIORITY,&task2_handle);
	task3_ret = xTaskCreate(task3,"task3",configMINIMAL_STACK_SIZE,NULL,TASK3_PRIORITY,&task3_handle);
	task4_ret = xTaskCreate(task4,"task4",configMINIMAL_STACK_SIZE,NULL,TASK4_PRIORITY,&task4_handle);

	if(task1_ret == pdTRUE)
	{
		/* task1 created successfully */
	}

	if(task2_ret == pdTRUE)
	{
		/* task2 created successfully */
	}

	if(task3_ret == pdTRUE)
	{
		/* task3 created successfully */
	}

	if(task4_ret == pdTRUE)
	{
		/* task4 created successfully */
	}

	vTaskStartScheduler();

	for( ;; );

	return 0;
}



void system_init(void)
{
	/* Enable external crystal clock 8 mHZ */
	MRCC_voidInitSysClock();
	/* Enable portA clock */
	MRCC_voidEnableClock(RCC_APB2 , IOPAEN);
	/* Enable portB clock */
	MRCC_voidEnableClock(RCC_APB2 , IOPBEN);
	/* initialize 7-segment */
	SEVSEG_voidInit();
}



void task1(void *pvParameter)
{
	char num = 1 ;
	BaseType_t ret = pdFALSE;
	for(;;)
	{
		ret = xSemaphoreTake(SevSeg_1,portMAX_DELAY);

		if(ret == pdTRUE)
		{
			SEVSEG1_voidDisplay(num);

			/* software delay */
			for(u64 i=0 ; i< 350000 ; i++);

			xSemaphoreGive(SevSeg_1);

		}

		vTaskDelay(500);

	}
}



void task2(void *pvParameter)
{
	char num = 2 ;
	BaseType_t ret = pdFALSE;
	for(;;)
	{
		ret = xSemaphoreTake(SevSeg_1,portMAX_DELAY);

		if(ret == pdTRUE)
		{
			SEVSEG1_voidDisplay(num);

			/* software delay */
			//for(u64 i=0 ; i< 350000 ; i++);

			xSemaphoreGive(SevSeg_1);

		}

		vTaskDelay(500);

	}
}



void task3(void *pvParameter)
{
	char num = 3 ;
	BaseType_t ret = pdFALSE;
	for(;;)
	{
		ret = xSemaphoreTake(SevSeg_2,portMAX_DELAY);

		if(ret == pdTRUE)
		{
			SEVSEG2_voidDisplay(num);

			/* software delay */
			for(u64 i=0 ; i< 350000 ; i++);

			xSemaphoreGive(SevSeg_2);

		}

		vTaskDelay(500);
	}

}



void task4(void *pvParameter)
{
	char num = 4 ;
	BaseType_t ret = pdFALSE;
	for(;;)
	{
		ret = xSemaphoreTake(SevSeg_2,portMAX_DELAY);

		if(ret == pdTRUE)
		{
			SEVSEG2_voidDisplay(num);

			/* software delay */
			//for(u64 i=0 ; i< 350000 ; i++);

			xSemaphoreGive(SevSeg_2);

		}

		vTaskDelay(500);
	}
}
















