/*
******************************************************************************
File:     main.c
Info:     Generated by Atollic TrueSTUDIO(R) 9.3.0   2022-07-25

The MIT License (MIT)
Copyright (c) 2019 STMicroelectronics

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.

******************************************************************************
*/

/*
 * this program is for porting FreeRTOS with STM32F103C8
 * in this project we created a task and an interupt
 * we use semaphore for synchronization between the task and the interrupt
 * and we use queue to send data between two tasks
*/



/* Includes */
#include "STD_TYPES.h"
#include "BIT_MATH.h"


#include "RCC_interface.h"
#include "DIO_interface.h"
#include "EXTI_interface.h"
#include "NVIC_interface.h"
#include "SEVSEG_interface.h"



#include "FreeRTOS.h"
#include "task.h"
#include "semphr.h"
#include "queue.h"


#define TASK1_PRIORITY			(3)
#define TASK2_PRIORITY			(4)



TaskHandle_t task1_handle = NULL , task2_handle = NULL ;

SemaphoreHandle_t sevseg = NULL;

QueueHandle_t Queue1 = NULL;

volatile int button_pressed = 0;


void task1(void *pvParameter);
void task2(void *pvParameter);


void EXTI_callback(void);

void system_init(void);




int main(void)
{

	system_init();

	BaseType_t task1_ret = pdFALSE , task2_ret = pdFALSE;

	sevseg = xSemaphoreCreateBinary();

	if(sevseg != NULL)
	{
		/* semaphore created successfully */
	}

	Queue1 = xQueueCreate(10,sizeof(unsigned char)) ;
	if( Queue1 == NULL )
	{
		/* Queue was not created and must not be used. */
	}

	task1_ret = xTaskCreate(task1,"task1",configMINIMAL_STACK_SIZE,NULL,TASK1_PRIORITY,&task1_handle);
	task2_ret = xTaskCreate(task2,"task2",configMINIMAL_STACK_SIZE,NULL,TASK2_PRIORITY,&task2_handle);


	if(task1_ret == pdTRUE)
	{
		/* task1 created successfully */
	}

	if(task2_ret == pdTRUE)
	{
		/* task2 created successfully */
	}


	vTaskStartScheduler();
	for(;;);

	return 0;
}




void system_init(void)
{
	/* Enable external crystal clock 8 mHZ */
	MRCC_voidInitSysClock();
	/* Enable portA clock */
	MRCC_voidEnableClock(RCC_APB2 , IOPAEN);
	/* Enable portB clock */
	MRCC_voidEnableClock(RCC_APB2 , IOPBEN);
	MEXTI_voidInit();

	/* Set PINA9 as Output NMHZ Push pull */
	MGPIO_voidSetPullResistor(PORTA,PIN0,GPIO_PULL_UP);

	MEXTI_voidSetSignalLatch(EXTI_LINE0,EXTI_FALLING);
	MEXTI_voidSetCallBack(EXTI_LINE0,EXTI_callback);

	/*
	 * very important note : we should set all priority bits as group priority
	 * and any interrupt priority uses FreeRTOS API must have lower priority than configMAX_SYSCALL_INTERRUPT_PRIORITY
	 * that means it must be more than it in value because zero is the highest priority
	 * for more information please visit this site : http://www.freertos.org/RTOS-Cortex-M3-M4.html
	 */
	MNVIC_voidSetPriority(EXTI0,8,0,NVIC_GROUP4_SUB0);

	MEXTI_voidEnableEXTI(EXTI_LINE0);

	MNVIC_voidEnableInterrupt(EXTI0);
	/* initialize 7-segment */
	SEVSEG_voidInit();
}



void task1(void *pvParameter)
{
	BaseType_t ret = pdFALSE;
	char num = 0 ;
	char var;
	for(;;)
	{
		ret = xSemaphoreTake(sevseg,portMAX_DELAY);
		if(ret == pdTRUE)
		{
			if(num ==10)
			{
				num = 0;
			}
			SEVSEG1_voidDisplay(num);

			/* software delay */
			//for(u64 i=0 ; i< 350000 ; i++);
			var = 9-num;
			xQueueSend(Queue1,&var,portMAX_DELAY);
			num++;
		}
		vTaskDelay(100);
	}
}



void task2(void *pvParameter)
{
	BaseType_t queue_ret = pdFALSE;
	unsigned char var;
	for(;;)
	{
		queue_ret = xQueueReceive(Queue1,&var,portMAX_DELAY);
		if(queue_ret == pdTRUE)
		{
			SEVSEG2_voidDisplay(var);
		}

		vTaskDelay(100);
	}
}


void EXTI_callback(void)
{
	BaseType_t ret = pdFALSE;
	ret = xSemaphoreGiveFromISR(sevseg,NULL);
	if(ret==pdTRUE)
	{
//		SEVSEG_voidDisplay(3);
//		for(u64 i=0 ; i< 350000 ; i++);
	}

}






